# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/message.proto',
  package='TestTask.Messages',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x63ommon/message.proto\x12\x11TestTask.Messages\"\x9c\x02\n\x0eWrapperMessage\x12\x36\n\rfast_response\x18\x01 \x01(\x0b\x32\x1f.TestTask.Messages.FastResponse\x12\x36\n\rslow_response\x18\x02 \x01(\x0b\x32\x1f.TestTask.Messages.SlowResponse\x12L\n\x19request_for_fast_response\x18\x03 \x01(\x0b\x32).TestTask.Messages.RequestForFastResponse\x12L\n\x19request_for_slow_response\x18\x04 \x01(\x0b\x32).TestTask.Messages.RequestForSlowResponse\")\n\x0c\x46\x61stResponse\x12\x19\n\x11\x63urrent_date_time\x18\x01 \x02(\t\".\n\x0cSlowResponse\x12\x1e\n\x16\x63onnected_client_count\x18\x01 \x02(\r\"\x18\n\x16RequestForFastResponse\":\n\x16RequestForSlowResponse\x12 \n\x18time_in_seconds_to_sleep\x18\x01 \x02(\r'
)




_WRAPPERMESSAGE = _descriptor.Descriptor(
  name='WrapperMessage',
  full_name='TestTask.Messages.WrapperMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fast_response', full_name='TestTask.Messages.WrapperMessage.fast_response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='slow_response', full_name='TestTask.Messages.WrapperMessage.slow_response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_for_fast_response', full_name='TestTask.Messages.WrapperMessage.request_for_fast_response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_for_slow_response', full_name='TestTask.Messages.WrapperMessage.request_for_slow_response', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=328,
)


_FASTRESPONSE = _descriptor.Descriptor(
  name='FastResponse',
  full_name='TestTask.Messages.FastResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_date_time', full_name='TestTask.Messages.FastResponse.current_date_time', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=371,
)


_SLOWRESPONSE = _descriptor.Descriptor(
  name='SlowResponse',
  full_name='TestTask.Messages.SlowResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='connected_client_count', full_name='TestTask.Messages.SlowResponse.connected_client_count', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=419,
)


_REQUESTFORFASTRESPONSE = _descriptor.Descriptor(
  name='RequestForFastResponse',
  full_name='TestTask.Messages.RequestForFastResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=445,
)


_REQUESTFORSLOWRESPONSE = _descriptor.Descriptor(
  name='RequestForSlowResponse',
  full_name='TestTask.Messages.RequestForSlowResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_in_seconds_to_sleep', full_name='TestTask.Messages.RequestForSlowResponse.time_in_seconds_to_sleep', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=505,
)

_WRAPPERMESSAGE.fields_by_name['fast_response'].message_type = _FASTRESPONSE
_WRAPPERMESSAGE.fields_by_name['slow_response'].message_type = _SLOWRESPONSE
_WRAPPERMESSAGE.fields_by_name['request_for_fast_response'].message_type = _REQUESTFORFASTRESPONSE
_WRAPPERMESSAGE.fields_by_name['request_for_slow_response'].message_type = _REQUESTFORSLOWRESPONSE
DESCRIPTOR.message_types_by_name['WrapperMessage'] = _WRAPPERMESSAGE
DESCRIPTOR.message_types_by_name['FastResponse'] = _FASTRESPONSE
DESCRIPTOR.message_types_by_name['SlowResponse'] = _SLOWRESPONSE
DESCRIPTOR.message_types_by_name['RequestForFastResponse'] = _REQUESTFORFASTRESPONSE
DESCRIPTOR.message_types_by_name['RequestForSlowResponse'] = _REQUESTFORSLOWRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WrapperMessage = _reflection.GeneratedProtocolMessageType('WrapperMessage', (_message.Message,), {
  'DESCRIPTOR' : _WRAPPERMESSAGE,
  '__module__' : 'common.message_pb2'
  # @@protoc_insertion_point(class_scope:TestTask.Messages.WrapperMessage)
  })
_sym_db.RegisterMessage(WrapperMessage)

FastResponse = _reflection.GeneratedProtocolMessageType('FastResponse', (_message.Message,), {
  'DESCRIPTOR' : _FASTRESPONSE,
  '__module__' : 'common.message_pb2'
  # @@protoc_insertion_point(class_scope:TestTask.Messages.FastResponse)
  })
_sym_db.RegisterMessage(FastResponse)

SlowResponse = _reflection.GeneratedProtocolMessageType('SlowResponse', (_message.Message,), {
  'DESCRIPTOR' : _SLOWRESPONSE,
  '__module__' : 'common.message_pb2'
  # @@protoc_insertion_point(class_scope:TestTask.Messages.SlowResponse)
  })
_sym_db.RegisterMessage(SlowResponse)

RequestForFastResponse = _reflection.GeneratedProtocolMessageType('RequestForFastResponse', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTFORFASTRESPONSE,
  '__module__' : 'common.message_pb2'
  # @@protoc_insertion_point(class_scope:TestTask.Messages.RequestForFastResponse)
  })
_sym_db.RegisterMessage(RequestForFastResponse)

RequestForSlowResponse = _reflection.GeneratedProtocolMessageType('RequestForSlowResponse', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTFORSLOWRESPONSE,
  '__module__' : 'common.message_pb2'
  # @@protoc_insertion_point(class_scope:TestTask.Messages.RequestForSlowResponse)
  })
_sym_db.RegisterMessage(RequestForSlowResponse)


# @@protoc_insertion_point(module_scope)
